ingress:
  enabled: true
  path: /$NAMESPACE
  hosts:
  - grafana.hellman.oxygen.dfds.cloud
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip

service:
  labels:
    delivered_by: devex

grafana.ini:
  server:
    domain: grafana.hellman.oxygen.dfds.cloud
    root_url: $ROOT_URL
    # serve_from_sub_path: true

rbac:
  create: true
  namespaced: true
  pspEnabled: false
  pspUseAppArmor: false

sidecar:
  dashboards:
    enabled: true
  datasources:
    enabled: true

plugins:
  - grafana-polystat-panel

notifiers:
  notifiers.yaml:
    notifiers:
      - name: slack-channel-1
        type: slack
        uid: notifier1
        org_id: 1
        is_default: true
        send_reminder: true
        frequency: 1h
        disable_resolve_message: false
        # See  section for settings supporter for each
        # alert notification type.
        settings:
          recipient: '#$SLACK_CHANNEL'
          uploadImage: true
          url: $SLACK_URL
          username: alertbot
