ingress:
  enabled: true
  path: /capability-vwxyz
  hosts:
  - grafana.hellman.oxygen.dfds.cloud
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip

grafana.ini:
  server:
    domain: grafana.hellman.oxygen.dfds.cloud
    root_url: "https://%(domain)s/capability-vwxyz"
    # serve_from_sub_path: true

rbac:
  namespaced: true
  pspEnabled: false
  pspUseAppAmor: false

sidecar:
  dashboards:
    enabled: true
  datasources:
    enabled: true

plugins:
  - grafana-polystat-panel

notifiers:
  notifiers.yaml:
    notifiers:
      - name: notification-channel-1
        type: slack
        uid: notifier1
        org_id: 1
        is_default: true
        send_reminder: true
        frequency: 1h
        disable_resolve_message: false
        # See  section for settings supporter for each
        # alert notification type.
        settings:
          recipient: "#hellman-alerting"
          uploadImage: true
          url: https://hooks.slack.com/services/XXXXXXXXX/YYYYYYYYY/ZZZZZZZZZZZZZZZZZZZZZZZZ
          username: alertbot
